@extends('layout.template')

@section('content')
<table class="table table-striped">
    <head>
        <tr>
            <th>No</th>
            <th>Nama</th>
            <th>NIM</th>
            <th>Kelas</th>
        </tr>
        <tr>
            <td>1</td>
            <td>Angel</td>
            <td>611</td>
            <td>A</td>
        </tr>
        <tr>
            <td>2</td>
            <td>Kaysen</td>
            <td>612</td>
            <td>B</td>
        </tr>
        <tr>
            <td>3</td>
            <td>Ell</td>
            <td>613</td>
            <td>A</td>
        </tr>
    </head>
</table>
@endsection
